// Authors: Jonathan Monreal (jem177) and Jiawei Wu (jxw585)

// The top-level Verilog file for eecs301_lab1
// This code was initially generated by Terasic System Builder

module eecs301_lab1(

         //////////// ADC //////////
         output ADC_CONVST,
         output ADC_DIN,
         input ADC_DOUT,
         output ADC_SCLK,

         //////////// CLOCK //////////
         input CLOCK_50,
         input CLOCK2_50,
         input CLOCK3_50,
         input CLOCK4_50,

         //////////// SEG7 //////////
         output [ 6: 0 ] HEX0,
         output [ 6: 0 ] HEX1,
         output [ 6: 0 ] HEX2,
         output [ 6: 0 ] HEX3,
         output [ 6: 0 ] HEX4,
         output [ 6: 0 ] HEX5,

         //////////// KEY //////////
         input [ 3: 0 ] KEY,

         //////////// LED //////////
         output [ 9: 0 ] LEDR,

         //////////// SW //////////
         input [ 9: 0 ] SW,

         //////////// VGA //////////
         output [ 7: 0 ] VGA_B,
         output VGA_BLANK_N,
         output VGA_CLK,
         output [ 7: 0 ] VGA_G,
         output VGA_HS,
         output [ 7: 0 ] VGA_R,
         output VGA_SYNC_N,
         output VGA_VS,

         //////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
         inout [ 35: 0 ] GPIO_0,

         //////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
         inout [ 35: 0 ] GPIO_1
       );

//=======================================================
//  REG/WIRE declarations
//=======================================================

wire c;
wire [2:0] llights, rlights;
wire [9:0] test;

//=======================================================
//  Structural coding
//=======================================================

assign LEDR[9:7] = llights;
assign LEDR[2:0] = rlights;
assign test = SW;


counter count(
          .clk( CLOCK_50 ),
          .counter_msb( c )
        );

turn insig(
	.clock(c),
	.left(test[1]),
	.right(test[0]),
	.l_signal(llights), .r_signal(rlights), .error()

);


endmodule
