
// The top-level Verilog file for eecs301_lab3
// This code was initially generated by Terasic System Builder

module eecs301_lab3(

         //////////// ADC //////////
         output ADC_CONVST,
         output ADC_DIN,
         input ADC_DOUT,
         output ADC_SCLK,

         //////////// CLOCK //////////
         input CLOCK_50,
         input CLOCK2_50,
         input CLOCK3_50,
         input CLOCK4_50,

         //////////// SEG7 //////////
         output [ 6: 0 ] HEX0,
         output [ 6: 0 ] HEX1,
         output [ 6: 0 ] HEX2,
         output [ 6: 0 ] HEX3,
         output [ 6: 0 ] HEX4,
         output [ 6: 0 ] HEX5,

         //////////// KEY //////////
         input [ 3: 0 ] KEY,

         //////////// LED //////////
         output [ 9: 0 ] LEDR,

         //////////// SW //////////
         input [ 9: 0 ] SW,

         //////////// VGA //////////
         output [ 7: 0 ] VGA_B,
         output VGA_BLANK_N,
         output VGA_CLK,
         output [ 7: 0 ] VGA_G,
         output VGA_HS,
         output [ 7: 0 ] VGA_R,
         output VGA_SYNC_N,
         output VGA_VS,

         //////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
         inout [ 35: 0 ] GPIO_0,

         //////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
         inout [ 35: 0 ] GPIO_1
       );

//=======================================================
//  REG/WIRE declarations
//=======================================================

reg SYNC;
reg SCLK;
reg Din;
reg LDAC;
reg CLR;
assign GPIO_0[10] = ~SYNC;
assign GPIO_0[8] = SCLK;
assign GPIO_0[9] = Din;
assign GPIO_0[11] = ~LDAC;
assign GPIO_0[12] = ~CLR;

// Switch and button definitions
wire variable = ~SW[0];
wire enable_SPI = ~SW[1];
wire reset = ~KEY[0];
wire down = ~KEY[1];
wire up = ~KEY[2];

// Amplitude and frequency registers
reg amplitude;
reg frequency;

// Temporary

assign LEDR = amplitude;
<<<<<<< HEAD

wire [17:0] nco_data;
wire sr_out;

=======
>>>>>>> b1c0d6dd5055eadc018c17d17f2e0c1824688db9

//=======================================================
//  Structural coding
//=======================================================

<<<<<<< HEAD
shiftreg sr(
	.clock(),
	.data(nco_data),
	.enable(),
	.load(),
	.shiftin(),
	.shiftout(sr_out)
)

NCO generator(
		.clk(CLOCK_50),       // clk.clk
		.clken(1),     //  in.clken
		.phi_inc_i(), //    .phi_inc_i
		.fsin_o(ncodata),    // out.fsin_o
=======
Module NCO generator(
		.clk(),       // clk.clk
		.clken(),     //  in.clken
		.phi_inc_i(), //    .phi_inc_i
		.fsin_o(),    // out.fsin_o
>>>>>>> b1c0d6dd5055eadc018c17d17f2e0c1824688db9
		.out_valid(), //    .out_valid
		.reset_n()

)

endmodule
